### ISSUE TITLE
use of urlPrefix for sourcemap upload

### ISSUE THREAD

**Issue by wyardley** [eclass/semantic-release-sentry-releases#652]
Can you explain the difference between `path` and `urlPrefix` for sourcemaps? I'm getting a situation where the plugin says sourcemaps are uploaded, but they're still empty in the interface

I have:
```yaml
  - path: '@eclass/semantic-release-sentry-releases'
    sourcemaps: build
    tagsUrl: https://github.com/myorg/somereporeleases/tag/
    urlPrefix: build
```
(other settings are coming from env vars)

The docs don't really explain beyond:
> URL prefix for sourcemaps. Example ~/dist. Optional for upload sourcemaps

(side note: from what I can see, it's _not_ optional, due to [this conditional](https://github.com/eclass/semantic-release-sentry-releases/blob/214075f5c5e53e0ad632e311427f6ff88b98b3f0/src/publish.js#L94)

The description in:
https://github.com/eclass/semantic-release-sentry-releases/blob/214075f5c5e53e0ad632e311427f6ff88b98b3f0/src/get-assets.js#L8-L9
refers to both urlPrefix and path as paths, though in the example, it seems like `path` is a relative path and `urlPrefix` is a full path (in the example), since it's prefixed with a tilde?

Also, can you explain what `rewrite` is for exactly?
